config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  root 'images#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def index
    @images = Image.all.order("created_at DESC")
  end
  
  def new
    @image = Image.new
  end
  def show
    @image = Image.find(params[:id])
  end
  def create
    @img = Image.new(image_params)
    
    if @img.save
      redirect_to Image.last
    else
      render 'new'
    end
  end
  
  private
    def image_params
      params.require(:image).permit(:title, :description, :author, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= simple_form_for @image do |f| %>
	<%= f.file_field :img %>
	<%= f.button :submit %>
<% end %>

app/views/images/index.html.erb
<% @images.each do |image| %>
	<%= image_tag image.img %>
<% end %>



<%= link_to "Add Image", new_image_path %>

app/views/images/new.html.erb
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ImageUpload</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
		<li>
			<button class="btn btn-default navbar-btn btn-md">
				<%= simple_form_for @image do |f| %>
				<%= f.file_field :img %>
			</button>

				<%= f.button :submit %>
				<% end %>

		</li>

              </ul>
            </li>
          </ul>
          <ul class="nav  navbar-right">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div class="newPage">


</div>

app/views/images/show.html.erb
<div class="row">

<%= image_tag @image.img,  :size => "260x180" %>

</div>

<%= link_to "← Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUpload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>